name: OSM

services:

  openstamanager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openstamanager
    restart: unless-stopped
    ports:
      - "8090:80"
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=openstamanager
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    volumes:
      - ./files:/var/www/html/files
      - ./backup:/var/www/html/backup

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: openstamanager
      MYSQL_ROOT_PASSWORD: secret
    command: 
      - --sort_buffer_size=2M
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db:/var/lib/mysql

volumes:
  db: